package com.aps.wicc.ejb.initialisation;

import org.apache.deltaspike.core.api.exclude.*;
import org.apache.deltaspike.core.api.projectstage.*;

import javax.inject.Inject;
import javax.persistence.*;

import com.aps.wicc.persist.*;
import com.aps.wicc.model.*;

@Exclude(ifProjectStage = { ProjectStage.Production.class })
@Secondary
public class ContingencyAlterationInitialisation implements Initialisable
{
	@Inject
    private EntityManager entityManager;
	
	@Inject
    private ServiceGroupDao serviceGroupDao;
    
    @Override
    public void init() {
        
    	ContingencyPlan contingencyPlan;
        
    	/*
        contingencyPlan = new ContingencyPlan.PlanBuilder()
        			.setCode("SRP1")
        			.setTitle("14tph reduction Raynes Park-Waterloo")
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("2L-B"))
        				.setDirection(Direction.FORWARD)
        				.setAffect(Affect.ALTERED)
        				.addAlteration(new Alteration(AlterationType.NEWDEST, "Woking")).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("2L-B"))
        				.setDirection(Direction.REVERSE)
        				.setAffect(Affect.ALTERED)
        				.addAlteration(new Alteration(AlterationType.NEWORIGIN, "Woking")).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("1A"))
        				.setDirection(Direction.FORWARD)
        				.setAffect(Affect.ALTERED)
        				.addAlteration(new Alteration(AlterationType.NEWDEST, "Woking")).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("2A"))
        				.setDirection(Direction.FORWARD)
        				.setAffect(Affect.ALTERED)
        				.addAlteration(new Alteration(AlterationType.NEWDEST, "Woking")).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("1A"))
        				.setDirection(Direction.REVERSE)
        				.setAffect(Affect.ALTERED)
        				.addAlteration(new Alteration(AlterationType.NEWORIGIN, "Woking")).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("2A"))
        				.setDirection(Direction.REVERSE)
        				.setAffect(Affect.ALTERED)
        				.addAlteration(new Alteration(AlterationType.NEWORIGIN, "Woking")).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("1L"))
        				.setDirection(Direction.FORWARD).setAffect(Affect.ALTERED)
        				.addAlteration(new Alteration(AlterationType.NEWDEST, "Basingstoke")).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("1L"))
        				.setDirection(Direction.REVERSE)
        				.setAffect(Affect.ALTERED)
        				.addAlteration(new Alteration(AlterationType.NEWORIGIN, "Basingstoke")).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("1D"))
        				.setDirection(Direction.BOTH).setAffect(Affect.CANCELLED).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("2M"))
        				.setDirection(Direction.BOTH)
        				.setAffect(Affect.CANCELLED).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("2J"))
        				.setDirection(Direction.BOTH)
        				.setAffect(Affect.CANCELLED).build())
        			.add(new ContingencyAlteration.Builder()
        				.setServiceGroup(this.serviceGroupDao.findByUid("2H"))
        				.setDirection(Direction.BOTH)
        				.setAffect(Affect.CANCELLED).build()).build();
        this.entityManager.persist(contingencyPlan);
        
        contingencyPlan = new ContingencyPlan.PlanBuilder()
                              .setCode("SRP2")
                              .setTitle("8tph reduction Raynes Park-Waterloo")
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("1L"))
                                 .setDirection(Direction.FORWARD)
                                 .setAffect(Affect.ALTERED)
                                 .addAlteration(new Alteration(AlterationType.NEWDEST, "Basingstoke")).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("1L"))
                                 .setDirection(Direction.REVERSE)
                                 .setAffect(Affect.ALTERED)
                                 .addAlteration(new Alteration(AlterationType.NEWORIGIN, "Basingstoke")).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("1D"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2M"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2J"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build()).build();
        this.entityManager.persist(contingencyPlan);
        
        contingencyPlan = new ContingencyPlan.PlanBuilder()
                              .setCode("SRP3")
                              .setTitle("Windsor Lines AM Peak")
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2R-W"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2V"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build()).build();
        this.entityManager.persist(contingencyPlan);
        
        contingencyPlan = new ContingencyPlan.PlanBuilder()
                              .setCode("SRP4")
                              .setTitle("Windsor Lines PM Peak")
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2R-W"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2V"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build()).build();
        this.entityManager.persist(contingencyPlan);
        
        contingencyPlan = new ContingencyPlan.PlanBuilder()
                              .setCode("SRP5")
                              .setTitle("Windsor Both Lines Barnes-Waterloo")
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2S"))
                                 .setDirection(Direction.FORWARD)
                                 .setAffect(Affect.ALTERED)
                                 .addAlteration(new Alteration(AlterationType.NEWDEST, "Kew Bridge")).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2U"))
                                 .setDirection(Direction.FORWARD)
                                 .setAffect(Affect.ALTERED)
                                 .addAlteration(new Alteration(AlterationType.RUNVIA, "Kingston")).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2C"))
                                 .setDirection(Direction.FORWARD)
                                 .setAffect(Affect.ALTERED)
                                 .addAlteration(new Alteration(AlterationType.RUNVIA, "Chertsey")).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2K"))
                                 .setDirection(Direction.FORWARD)
                                 .setAffect(Affect.ALTERED)
                                 .addAlteration(new Alteration(AlterationType.NEWDEST, "Richmond")).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2R-W"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2V"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("2H"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("1C"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build())
                              .add(new ContingencyAlteration.Builder()
                                 .setServiceGroup(this.serviceGroupDao.findByUid("1N"))
                                 .setDirection(Direction.BOTH)
                                 .setAffect(Affect.CANCELLED).build()).build();
        this.entityManager.persist(contingencyPlan);        
        */
    	
    	
    	contingencyPlan = new ContingencyPlan.PlanBuilder()
        .setCode("SRP1Y")
        .setTitle("SRP Yellow 1: Mainline 8tph")
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1L"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.STARTFINISH, "Basingstoke"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1D"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.CANCELLED)
            .setDelay("")
            .setFreeform("")
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2M"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.CANCELLED)
            .setDelay("")
            .setFreeform("")
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2J"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.CANCELLED)
            .setDelay("")
            .setFreeform("")
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1W"))
            .setDirection(Direction.REVERSE)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.CALLADD, "Clapham Jn"))
                .addAlteration(new Alteration(AlterationType.CALLADD, "Woking"))
                .addAlteration(new Alteration(AlterationType.CALLADD, "Basingstoke"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2G"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.CALLADD, "Berrylands"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1T"))
            .setDirection(Direction.FORWARD)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.NOTCALL, "Farnborough"))
                .addAlteration(new Alteration(AlterationType.NOTCALL, "Fleet"))
            .build())
        .build();    
    this.entityManager.persist(contingencyPlan);
    
    contingencyPlan = new ContingencyPlan.PlanBuilder()
        .setCode("SRP1R")
        .setTitle("SRP  Red 1: Mainline 12tph")
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1L"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.STARTFINISH, "Basingstoke"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2H"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.RUNVIA, "Twickenham"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1P"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.STARTFINISH, "Woking"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2F"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.CANCELLED)
            .setDelay("")
            .setFreeform("")
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1D"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.CANCELLED)
            .setDelay("")
            .setFreeform("")
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2M"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.CANCELLED)
            .setDelay("")
            .setFreeform("")
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2J"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.CANCELLED)
            .setDelay("")
            .setFreeform("")
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1W"))
            .setDirection(Direction.REVERSE)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.CALLADD, "Clapham Jn"))
                .addAlteration(new Alteration(AlterationType.CALLADD, "Woking"))
                .addAlteration(new Alteration(AlterationType.CALLADD, "Basingstoke"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2G"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.CALLADD, "Berrylands"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("2L"))
            .setDirection(Direction.BOTH)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.CALLADD, "all stations Woking to Surbiton"))
            .build())
        .add(new ContingencyAlteration.Builder()
            .setServiceGroup(this.serviceGroupDao.findByUid("1T"))
            .setDirection(Direction.FORWARD)
            .setAffect(Affect.ALTERED)
            .setDelay("")
            .setFreeform("")
                .addAlteration(new Alteration(AlterationType.NOTCALL, "Farnborough"))
                .addAlteration(new Alteration(AlterationType.NOTCALL, "Fleet"))
            .build())
        .build();    
    this.entityManager.persist(contingencyPlan);

       
    }
}
